# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoresRow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('snpid', models.CharField(max_length=40)),
                ('motif', models.CharField(max_length=20)),
                ('motif_len', models.IntegerField(default=0)),
                ('log_lik_ref', models.FloatField(default=0)),
                ('log_lik_snp', models.FloatField(default=0)),
                ('log_lik_ratio', models.FloatField(default=0)),
                ('log_enhance_odds', models.FloatField(default=0)),
                ('log_reduce_odds', models.FloatField(default=0)),
                ('ref_start', models.IntegerField(default=0)),
                ('snp_start', models.IntegerField(default=0)),
                ('ref_end', models.IntegerField(default=0)),
                ('snp_end', models.IntegerField(default=0)),
                ('ref_strand', models.CharField(default='', max_length=1)),
                ('snp_strand', models.CharField(default='', max_length=1)),
            ],
            options={
                'db_table': 'snp_scores_1',
                'managed': False,
            },
        ),
    ]
